<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>

        <AssemblyName>EasyMQ</AssemblyName>
        <RootNamespace>EasyMQ</RootNamespace>
        <Version>1.2.0</Version>
        <Authors>Mehdi Mehrabadi</Authors>
        <PackageId>EasyMQ</PackageId>
        <PackageTags>aspnetcore;easymq;rabbitmq;queue</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/MehdiMehrabadi/EasyMQ</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/MehdiMehrabadi/EasyMQ</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <Description>A package for easier use of RabbitMQ with professional queue management</Description>


        <LangVersion>preview</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>


        <NuspecFile>EasyMQ.nuspec</NuspecFile>
        <NuspecProperties>version=$(Version)</NuspecProperties>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0"/>
        <PackageReference Include="RabbitMQ.Client" Version="7.2.2"/>
    </ItemGroup>
</Project>